name: blob-uploader
channels:
  - conda-forge
dependencies:
  - python=3.12.3
  - pip
  - python-dotenv==1.0.1
  - pip:
      - streamlit==1.51.0
      - azure-storage-blob
      - python-dotenv
      - pandas
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.0
      - gitdb==4.0.12
      - GitPython==3.1.45
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - googleapis-common-protos==1.72.0
      - httplib2==0.31.0
      - idna==3.11
      - Jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - MarkupSafe==3.0.3
      - matplotlib==3.10.7
      - narwhals==2.13.0
      - nltk==3.9.2
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.5.0
      - proto-plus==1.26.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.2
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rpds-py==0.30.0
      - rsa==4.9.1
      - seaborn==0.13.2
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.1
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing_extensions==4.15.0
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.6.0
      - watchdog==6.0.0

